name: Deploy to Hugging Face

on:
  push:
    branches:
      - main  # ✅ Only deploy on main branch changes

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Push to Hugging Face
        run: |
          # 🧠 Set Git identity
          git config --global user.email "info.shiladityamallick@gmail.com"
          git config --global user.name "By Shiladitya Mallick"

          # 🧽 Clone HF Space cleanly
          git clone https://huggingface.co/spaces/byshiladityamallick/neura-smart-assistant space
          cd space
          git reset --hard origin/main
          git clean -fdx
          cd ..

          # 📦 Copy this repo into HF space repo (excluding itself)
          rsync -av --exclude='.git' --exclude='space' ./ space || [[ $? == 24 ]]

          # 🕒 Touch a timestamp file to force commit
          date > space/.last_deployed_at.txt

          # ✅ Commit & push to HF
          cd space
          git add .
          git commit -m "🚀 Deploy from GitHub Action at $(date)" || echo "Nothing to commit"
          git push -f https://byshiladityamallick:${{ secrets.HF_TOKEN_WRITE }}@huggingface.co/spaces/byshiladityamallick/neura-smart-assistant main
