name: Deploy to Hugging Face

on:
  push:
    branches:
      - main  # ✅ Only deploy when main branch is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Push to Hugging Face
        run: |
          # Configure Git identity
          git config --global user.email "info.shiladityamallick@gmail.com"
          git config --global user.name "By Shiladitya Mallick"

          # Clone Hugging Face Space into ./space directory
          git clone https://huggingface.co/spaces/byshiladityamallick/neura-smart-assistant space

          # Copy all project files into the cloned repo, excluding .git, and delete anything extra
          rsync -av --exclude='.git' --delete ./ space || [[ $? == 24 ]]

          # Commit and push to HF Space
          cd space
          git add .
          git commit -m "Deploy from GitHub Action" || echo "Nothing to commit"
          git push https://byshiladityamallick:${{ secrets.HF_TOKEN_WRITE }}@huggingface.co/spaces/byshiladityamallick/neura-smart-assistant main
