name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🧽 Clone and Clean HF Space
        run: |
          # Git identity
          git config --global user.email "info.shiladityamallick@gmail.com"
          git config --global user.name "By Shiladitya Mallick"

          # Clone HF Space
          git clone https://huggingface.co/spaces/byshiladityamallick/neura-smart-assistant hf_space

          # Clean out old files
          cd hf_space
          git rm -rf . > /dev/null 2>&1 || true
          git clean -fdx
          cd ..

          # Copy only what we want (not .git or space/)
          rsync -av --exclude='.git' --exclude='hf_space' ./ hf_space/

          # Force redeploy with timestamp
          date > hf_space/.last_deployed_at.txt

          # Commit and push
          cd hf_space
          git add .
          git commit -m "🔥 Force deploy $(date)" || echo "Nothing to commit"
          git push -f https://byshiladityamallick:${{ secrets.HF_TOKEN_WRITE }}@huggingface.co/spaces/byshiladityamallick/neura-smart-assistant main
